language: cpp

install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install git help2man perl python3 make autoconf g++ flex bison ccache
  - sudo apt-get install libgoogle-perftools-dev numactl perl-doc
  - sudo apt-get install libfl2
  - sudo apt-get install libfl-dev
  - sudo apt-get install zlibc zlib1g zlib1g-dev
  - git clone https://github.com/verilator/verilator
  - cd verilator
  - git pull
  - git checkout stable
  - autoconf
  - ./configure
  - make -j `nproc
  - sudo make install

script:
  - verilator -Wall --trace -cc hvsync_generator.v --exe tb_hvsync_generator.cpp
  - make -C obj_dir -f Vhvsync_generator.mk Vhvsync_generator
  - ./obj_dir/Vhvsync_generator